### ISSUE TITLE
How to load latest issue by default?

### ISSUE THREAD

**Issue by ANONIMNIQ** [technomancy-dev/technonomicon#2]
I want when someone open my site latest issue number to open on main page by default. Also, how to keep track current issue number on top right corner when someone click read more for any article, right now always number change to issue 1.

**Comment by liltechnomancer** [comment]
To always show the latest issue, you could change [this line](https://github.com/technomancy-dev/technonomicon/blob/358387ea30afc75db7d419cd12cba3616b9d22d7/src/pages/index.astro#L5C1-L5C77) 

To something like 

```
const entry = await getCollection("issues").sort((a, b) => b.issueNumber - a.issueNumber)[0];
```

The issue in the top right should be driven by the issue number in the article. It looks like I have all those currently set to 1 which is incorrect, but you should be able to update that on your site and it should work fine. If not please let me know because that is a bug. Thanks for trying out my project!

**Comment by ANONIMNIQ** [comment]
Thank you, this works perfect!

**Comment by liltechnomancer** [comment]
Awesome! Closing this issue then. I am going to collect some sites for an examples section let me know if you would like to be included!
